// Users

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

export const GET_PHONES_SUCCESS='GET_PHONES_SUCCESS';

export const ADD_PHONE_SUCCESS='ADD_PHONE_SUCCESS';

export const ADD_PHONE_FAILURE='ADD_PHONE_FAILURE';

export const PHONE_PROFILE_SUCCESS='PHONE_PROFILE_SUCCESS';

export const GET_MORE_PHONES_SUCCESS='GET_MORE_PHONES_SUCCESS';
