// Users

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

export const GET_PHONES_SUCCESS='GET_PHONES_SUCCESS';

export const ADD_PHONE_SUCCESS='ADD_PHONE_SUCCESS';

export const ADD_PHONE_FAILURE='ADD_PHONE_FAILURE';
